FROM alpine:3.11

ENV BUILD_PACKAGES="\
    gcc \
    geos-dev \
    git \
    linux-headers \
    musl-dev \
    python3-dev \
    "
ENV REQUIREMENTS_WHEEL_PACKAGES="\
    cython \
    py3-gdal \
    py3-scipy \
    # following for geopandas
    build-base \
    gdal-dev \
    musl-dev \
    proj-dev \
    proj-util \
    python3-dev \
    py3-numpy-dev \
    "

RUN apk update && apk add $BUILD_PACKAGES $REQUIREMENTS_WHEEL_PACKAGES
RUN python3 -m ensurepip && pip3 install --upgrade pip
RUN pip3 install --upgrade pip pep517 wheel
