name: Upload Python Package

# on:
#   release:
#     types: [published]

on:
  push:
    branches: [ pypi ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          # noninteractive is necessary to install libgdal-dev
          # which is needed for python gdal which is
          # required by rasterio
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update && sudo apt-get install python3 python3-pip python3-venv libgdal-dev -y
          pip3 install build
      - name: Build package
        run: python3 -m build --outdir build .
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/*.whl

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: build/
          verbose: true

    # - name: Publish package
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     password: ${{ secrets.PYPI_API_TOKEN }}
    #     packages_dir: build/
    #     verbose: true
