name:  Test SBOM Vulnerability Scan - pyproject

on:
  push:
    branches:
      - add-grype-vulnerability-scan

jobs:
  sbom-scan:
    permissions:
      contents: read
      security-events: write

    uses: TaniaGithub0401/github-workflows/.github/workflows/sbom-vulnerability-scan.yml@add-reusable-sbom-vulnerability-workflow
    with:
        pyproject: pyproject.toml
        fail-build: false