name: Generate Third-Party Licenses

on:
  release:
    types: [published]

jobs:
  generate-third-party-licenses:
    uses: mundialis/github-workflows/.github/workflows/third-party-licenses.yml@main
    with:
      dockerfile: docker/actinia-core-alpine/Dockerfile
